name: chatbot_gemini
description: "A chatbot built with Flutter framework and powered by Gemini API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  gradient_borders: ^1.0.1
  http: ^1.2.2
  provider: ^6.1.2
  google_generative_ai: ^0.4.6
  add_2_calendar: ^3.0.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.3
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
          weight: 400
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700

flutter_native_splash:
  image: assets/images/splash.png
  color: "E1F5FE"
  android_12:
    image: assets/images/splash.png
